# MATH 210 Introduction to Mathematical Computing

**April 8, 2026**

In [1]:
import numpy as np
import scipy.linalg as la

In [2]:
A = np.array([[1.,2.],[2.,1.]])
print(A)

[[1. 2.]
 [2. 1.]]


In [3]:
D,P = la.eig(A)

In [4]:
D

array([ 3.+0.j, -1.+0.j])

In [5]:
np.real(D)

array([ 3., -1.])

In [6]:
P

array([[ 0.70710678, -0.70710678],
       [ 0.70710678,  0.70710678]])

In [7]:
1/2**0.5

0.7071067811865475

In [8]:
D = np.diag(D.real)
D

array([[ 3.,  0.],
       [ 0., -1.]])

In [9]:
P @ D @ la.inv(P)

array([[1., 2.],
       [2., 1.]])

In [10]:
A @ A @ A @ A @ A

array([[121., 122.],
       [122., 121.]])

In [11]:
P @ np.diag([3**5,(-1)**5]) @ la.inv(P)

array([[121., 122.],
       [122., 121.]])